version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Ubuntu2204
clone_folder: ~/project
build_script:
- sh: python3 ~/project/build.py
test: off
artifacts:
- path: output/*.zip
  name: plugs
deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: v$(APPVEYOR_BUILD_VERSION)
  description: Auto Build v$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: hHwoegRebR2QKq4GT3QmRhTxPjrcAtIFBIufsPmzhySfbjqFP2zAKmiGLICXNpqH
  artifact: plugs
  force_update: true